# Generated by Django 4.2.2 on 2023-07-18 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='admin_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='phone_number',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='on_trial',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='paid_until',
            field=models.DateField(blank=True, null=True),
        ),
    ]
