# Generated by Django 4.2.2 on 2023-06-29 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='company_worked_for',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='country',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
