# Generated by Django 4.2.2 on 2023-06-30 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_rename_company_worked_for_staff_company_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(blank=True, max_length=150, null=True)),
                ('message', models.TextField(max_length=1000)),
                ('send_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
