# Generated by Django 4.2.2 on 2023-06-30 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_contacts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacts',
            options={'ordering': ['-send_at']},
        ),
        migrations.AddField(
            model_name='contacts',
            name='replied',
            field=models.BooleanField(default=False),
        ),
    ]
