# Generated by Django 4.2.2 on 2023-06-30 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_tablebooking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tablebooking',
            old_name='number',
            new_name='people',
        ),
    ]
