# Generated by Django 4.2.2 on 2023-06-30 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_rename_number_tablebooking_people'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='static/img')),
                ('job_position', models.CharField(blank=True, max_length=150, null=True)),
                ('review_message', models.TextField(max_length=1000)),
                ('featured', models.BooleanField(blank=True, default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
