# Generated by Django 4.2.2 on 2023-06-30 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_customerreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/img')),
                ('event', models.CharField(blank=True, help_text='event the image was taken or name of the image', max_length=50, null=True)),
                ('short_description', models.TextField(blank=True, help_text='event the image was taken or name of the image', max_length=250, null=True)),
                ('facebook', models.URLField(blank=True, help_text='facebook link to the image post if was shared', null=True)),
                ('twitter', models.URLField(blank=True, help_text='twitter link to the image tweet if was shared', null=True)),
                ('instagram', models.URLField(blank=True, help_text='instagram link to the image post if was shared', null=True)),
                ('linkedin', models.URLField(blank=True, help_text='linkedin link to the image post if was shared', null=True)),
                ('featured', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
    ]
