# Generated by Django 4.2.2 on 2023-07-01 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_aboutus_created_at_aboutus_updated_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='call',
            new_name='call2',
        ),
        migrations.AddField(
            model_name='company',
            name='email2',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
