# Generated by Django 4.2.2 on 2023-07-02 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_remove_menu_category_menu_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='served',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
